export class UpdateTutorDto {
  language: string;
  occupation: string;
  secondaryschool: string;
  primaryschool: string;
  yearofexperience: string;
  experience: string;
  highestteachinglevel: string;
  educationallevel: string;
  notes: string;
  schoolcat: string;
  year: number | null;
  publicexamgrade: string;
  university: string | null;
  othercert: string | null;
  major: string | null;
  subgrade: string | null;
  strength: string;
  highestfee: number;
  lowestfee: number;
  matchedbefore: boolean | null;
  status: string;
  lastOnline: string;
  verify: string;
  completeFormStatus: number;
  locations: string[];
  subjects: string[];
  availtimes: string[];
  subjectGrade: string | null;
}
