export const dummyTutor = {
  location: '[]',
  availtime: '[]',
  intro: null,
  language: null,
  occupation: null,
  secondaryschool: null,
  primaryschool: null,
  yearofexperience: null,
  experience: null,
  highestteachinglevel: null,
  educationallevel: null,
  notes: null,
  schoolcat: null,
  year: null,
  publicexamgrade: null,
  university: null,
  othercert: null,
  caseid: null,
  major: null,
  subgrade: '[]',
  strength: null,
  fee: null,
  subject: '[]',
};
